version: '3.8'

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy:latest
        container_name: nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./volumes/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
            - ./volumes/vhost.d:/etc/nginx/vhost.d
            - ./volumes/html:/usr/share/nginx/html
            - ./volumes/certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always
        networks:
            - nginx-proxy

    acme-companion:
        image: nginxproxy/acme-companion:latest
        container_name: nginx-proxy-acme
        environment:
            DEFAULT_EMAIL: ${DEFAULT_EMAIL}
        volumes_from:
            - nginx-proxy
        volumes:
            - ./volumes/certs:/etc/nginx/certs:rw
            - ./volumes/acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - nginx-proxy
        restart: always
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        name: nginx-proxy
